image: golang:latest

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/slick-agent
    artifacts:
      paths:
        - slick-agent

